In [1]:
import requests
import os
import json
import time
import pandas as pd
import sys
import os
import numpy as np
from datetime import date

current_dir = os.getcwd()
project_root = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.insert(0, project_root)

import src.modify_reps
import src.gen_committees

In [2]:
try: 
    df = pd.read_json(os.path.join(project_root, "src", "generated_outputs", "congressmen.json"))
except Exception as e:
    print("There is an issue with the congressmen.json. Quitting.")
    sys.exit()

try: 
    vote_df = pd.read_json(os.path.join(project_root, "src", "generated_outputs", "vote_avg.json"))
except Exception as e:
    print("There is an issue with the vote_avg.json. Quitting.")
    sys.exit()

In [3]:
df[df['bioguideID']=="W000194"]

,bioguideID,name,partyName,state,url,attribution,imageUrl,chamber,endYear,startYear
489,W000194,"Watkins, Wes",Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,1991.0,1977
490,W000194,"Watkins, Wes",Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,2003.0,1997

Run all the modify_reps.py steps

In [4]:
debug = 0

df = src.modify_reps.update_endyear(df)
df = src.modify_reps.add_tenure(df)
df = src.modify_reps.normalize_name(df)
df = src.modify_reps.only_current(df)
df = src.modify_reps.merge_in_voting_records(df, vote_df)
df = src.modify_reps.replace_democratic(df)

#Functions you need to do on merged vote and reps:
df = src.modify_reps.get_voter_rank(df)

comm_dict = src.gen_committees.gen_committees()
df = src.modify_reps.merge_in_comms(df, comm_dict)




#df[df['bioguideID']=='W000194']

2025-12-11 15:45:37,294 - gen_committees.py - WARNING - Comcode not found for P000197, Nonetype returned.
2025-12-11 15:45:37,295 - gen_committees.py - WARNING - Comcode not found for S001176, Nonetype returned.
2025-12-11 15:45:37,295 - gen_committees.py - WARNING - Comcode not found for J000299, Nonetype returned.
2025-12-11 15:45:37,296 - gen_committees.py - WARNING - Comcode not found for C001101, Nonetype returned.
2025-12-11 15:45:37,297 - gen_committees.py - WARNING - Comcode not found for None, Nonetype returned.
2025-12-11 15:45:37,298 - gen_committees.py - WARNING - Comcode not found for J000294, Nonetype returned.
2025-12-11 15:45:37,298 - gen_committees.py - WARNING - Comcode not found for V000139, Nonetype returned.

Now for some stats, for your reference:

In [5]:
print(comm_dict)

{'B001323': ['Committee on Natural Resources', 'Committee on Transportation and Infrastructure', 'Committee on Science, Space, and Technology', 'Vice Chair: Committee on Natural Resources: Energy and Mineral Resources', 'Committee on Natural Resources: Oversight and Investigations', 'Committee on Transportation and Infrastructure: Aviation', 'Committee on Transportation and Infrastructure: Coast Guard and Maritime Transportation', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials', 'Committee on Science, Space, and Technology: Environment', 'Committee on Science, Space, and Technology: Energy', 'Committee on Science, Space, and Technology: Investigations and Oversight'], 'M001212': ['Committee on Agriculture', 'Committee on the Judiciary', 'Vice Chair: Committee on Agriculture: Forestry and Horticulture', 'Committee on Agriculture: General Farm Commodities, Risk Management, and Credit', 'Committee on Agriculture: Livestock, Dairy, and Poultry', 'Committee on the Judiciary: Immigration Integrity, Security, and Enforcement', 'Committee on the Judiciary: Crime and Federal Government Surveillance', 'Committee on the Judiciary: Oversight'], 'F000481': ['Committee on Agriculture', 'Committee on Transportation and Infrastructure', 'Committee on Agriculture: Nutrition and Foreign Agriculture', 'Committee on Agriculture: Commodity Markets, Digital Assets, and Rural Development', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Economic Development, Public Buildings, and Emergency Management'], 'R000575': ['Chair: Committee on Armed Services'], 'A000055': ['Committee on Appropriations', 'Committee on Appropriations: Agriculture, Rural Development, Food and Drug Administration, and Related Agencies', 'Committee on Appropriations: Defense', 'Chair: Committee on Appropriations: Labor, Health and Human Services, Education, and Related Agencies'], 'S001220': ['Committee on Appropriations', 'Committee on Homeland Security', 'Vice Chair: Committee on Appropriations: Commerce, Justice, Science, and Related Agencies', 'Committee on Appropriations: Transportation, Housing and Urban Development, and Related Agencies', 'Committee on Appropriations: Legislative Branch', 'Committee on Homeland Security: Oversight, Investigations, and Accountability', 'Chairman: Committee on Homeland Security: Emergency Management and Technology'], 'P000609': ['Committee on Oversight and Government Reform', 'Committee on Energy and Commerce', 'Committee on Oversight and Government Reform: Economic Growth, Energy Policy, and Regulatory Affairs', 'Committee on Oversight and Government Reform: Government Operations', 'Committee on Energy and Commerce: Oversight and Investigations', 'Committee on Energy and Commerce: Energy', 'Chair: Committee on Energy and Commerce: Environment'], 'S001185': ['Committee on House Administration', 'Joint Committee on Printing', 'Committee on Ways and Means', 'Committee on House Administration: Elections', 'Committee on Ways and Means: Social Security', 'Committee on Ways and Means: Trade', 'Committee on Ways and Means: Oversight'], 'C001087': ['Committee on Agriculture', 'Chairman: Permanent Select Committee on Intelligence', 'Vice Chair: Committee on Transportation and Infrastructure', 'Committee on Agriculture: General Farm Commodities, Risk Management, and Credit', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit'], 'H001072': ['Chair: Committee on Financial Services', 'Permanent Select Committee on Intelligence', 'Permanent Select Committee on Intelligence: National Security Agency and Cyber', 'Permanent Select Committee on Intelligence: National Intelligence Enterprise'], 'W000809': ['Committee on Appropriations', 'Committee on Appropriations: Defense', 'Chair: Committee on Appropriations: Transportation, Housing and Urban Development, and Related Agencies', 'Committee on Appropriations: Financial Services and General Government'], 'W000821': ['Chair: Committee on Natural Resources', 'Committee on Transportation and Infrastructure', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials'], 'R000600': ['Committee on Foreign Affairs', 'Committee on Natural Resources', "Committee on Veterans' Affairs", 'Committee on Foreign Affairs: East Asia and Pacific', 'Committee on Foreign Affairs: Africa', 'Committee on Natural Resources: Water, Wildlife and Fisheries', 'Vice Chair: Committee on Natural Resources: Indian and Insular Affairs', "Committee on Veterans' Affairs: Oversight and Investigations", "Committee on Veterans' Affairs: Disability Assistance and Memorial Affairs"], 'S001183': ['Chairman: Joint Economic Committee', 'Committee on Ways and Means', 'Committee on Ways and Means: Tax', 'Chair: Committee on Ways and Means: Oversight'], 'C001132': ['Committee on Oversight and Government Reform', 'Committee on Homeland Security', 'Committee on Oversight and Government Reform: Military and Foreign Affairs', 'Committee on Oversight and Government Reform: Cybersecurity, Information Technology, and Government Innovation', 'Committee on Homeland Security: Transportation and Maritime Security', 'Committee on Homeland Security: Border Security and Enforcement'], 'A000381': ['Committee on Oversight and Government Reform', 'Committee on Natural Resources', 'Committee on Oversight and Government Reform: Economic Growth, Energy Policy, and Regulatory Affairs', 'Committee on Oversight and Government Reform: Cybersecurity, Information Technology, and Government Innovation', 'Committee on Natural Resources: Energy and Mineral Resources', 'Committee on Natural Resources: Oversight and Investigations'], 'S001211': ['Committee on Foreign Affairs', 'Committee on Transportation and Infrastructure', 'Select Committee on the  Strategic Competition Between the United States and the Chinese Communist Party', 'Committee on Foreign Affairs: Western Hemisphere', 'Committee on Transportation and Infrastructure: Aviation', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Economic Development, Public Buildings, and Emergency Management'], 'B001302': ['Committee on Oversight and Government Reform', 'Committee on the Judiciary', 'Committee on Oversight and Government Reform: Military and Foreign Affairs', 'Committee on Oversight and Government Reform: Federal Law Enforcement', 'Committee on the Judiciary: Immigration Integrity, Security, and Enforcement', 'Chair: Committee on the Judiciary: Crime and Federal Government Surveillance'], 'C001133': ['Committee on Appropriations', "Committee on Veterans' Affairs", 'Committee on Appropriations: National Security, Department of State, and Related Programs', 'Vice Chair: Committee on Appropriations: Homeland Security', 'Committee on Appropriations: Transportation, Housing and Urban Development, and Related Agencies', "Committee on Veterans' Affairs: Oversight and Investigations", "Committee on Veterans' Affairs: Economic Opportunity"], 'G000606': ['Committee on Education and Workforce', 'Committee on Natural Resources', 'Committee on Education and Workforce: Higher Education and Workforce Development', 'Committee on Education and Workforce: Early Childhood, Elementary, and Secondary Education'], 'H001098': ['Committee on Armed Services', "Committee on Veterans' Affairs", 'Committee on Armed Services: Tactical Air and Land Forces', 'Committee on Armed Services: Intelligence and Special Operations', 'Committee on Armed Services: Strategic Forces', "Committee on Veterans' Affairs: Health", "Committee on Veterans' Affairs: Economic Opportunity"], 'G000565': ['Committee on Oversight and Government Reform', 'Committee on Natural Resources', 'Committee on Oversight and Government Reform: Health Care and Financial Services', 'Committee on Oversight and Government Reform: Federal Law Enforcement', 'Committee on Natural Resources: Energy and Mineral Resources', 'Chair: Committee on Natural Resources: Oversight and Investigations'], 'L000578': ['Committee on Agriculture', 'Committee on Natural Resources', 'Committee on Transportation and Infrastructure', 'Chairman: Committee on Agriculture: Forestry and Horticulture', 'Committee on Agriculture: General Farm Commodities, Risk Management, and Credit', 'Committee on Natural Resources: Water, Wildlife and Fisheries', 'Committee on Natural Resources: Indian and Insular Affairs', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials'], 'H001068': ['Committee on Natural Resources', 'Committee on Transportation and Infrastructure', 'Committee on Natural Resources: Energy and Mineral Resources', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit'], 'K000401': ['Committee on Education and Workforce', 'Committee on the Judiciary', 'Committee on Transportation and Infrastructure', 'Committee on Education and Workforce: Higher Education and Workforce Development', 'Chairman: Committee on Education and Workforce: Early Childhood, Elementary, and Secondary Education', 'Committee on the Judiciary: Courts, Intellectual Property, Artificial Intelligence, and the Internet', 'Committee on the Judiciary: Crime and Federal Government Surveillance', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Economic Development, Public Buildings, and Emergency Management'], 'T000460': ['Committee on Ways and Means', 'Committee on Ways and Means: Health', 'Committee on Ways and Means: Tax'], 'M001177': ['Committee on the Budget', 'Committee on Natural Resources', 'Committee on the Judiciary', 'Committee on Natural Resources: Federal Lands', 'Committee on Natural Resources: Water, Wildlife and Fisheries', 'Chair: Committee on the Judiciary: Immigration Integrity, Security, and Enforcement', 'Committee on the Judiciary: The Constitution and Limited Government'], 'B001287': ['Committee on Foreign Affairs', 'Permanent Select Committee on Intelligence', 'Committee on Foreign Affairs: East Asia and Pacific', 'Committee on Foreign Affairs: South and Central Asia', 'Permanent Select Committee on Intelligence: National Security Agency and Cyber', 'Permanent Select Committee on Intelligence: National Intelligence Enterprise'], 'M001163': ['Committee on Energy and Commerce', 'Committee on Energy and Commerce: Energy', 'Committee on Energy and Commerce: Communications and Technology'], 'G000559': ['Committee on Armed Services', 'Committee on Transportation and Infrastructure', 'Committee on Armed Services: Readiness', 'Committee on Armed Services: Strategic Forces', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Coast Guard and Maritime Transportation', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Economic Development, Public Buildings, and Emergency Management'], 'H001090': ['Committee on Appropriations', 'Committee on Appropriations: Interior, Environment, and Related Agencies', 'Committee on Appropriations: Labor, Health and Human Services, Education, and Related Agencies'], 'D000623': ['Committee on Education and Workforce', 'Committee on Transportation and Infrastructure', 'Committee on Ethics', 'Committee on Education and Workforce: Health, Employment, Labor, and Pensions', 'Committee on Education and Workforce: Higher Education and Workforce Development', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Aviation', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials'], 'P000197': [], 'S001231': ['Committee on Oversight and Government Reform', 'Committee on Small Business', 'Committee on Oversight and Government Reform: Health Care and Financial Services', 'Committee on Oversight and Government Reform: Federal Law Enforcement', 'Committee on Small Business: Innovation, Entrepreneurship, and Workforce Development', 'Committee on Small Business: Oversight, Investigations, and Regulations'], 'G000605': ['Committee on Agriculture', 'Committee on Natural Resources', 'Committee on Agriculture: Forestry and Horticulture', 'Committee on Agriculture: Commodity Markets, Digital Assets, and Rural Development', 'Committee on Agriculture: Livestock, Dairy, and Poultry', 'Committee on Natural Resources: Water, Wildlife and Fisheries'], 'S001193': ['Committee on Homeland Security', 'Committee on the Judiciary', 'Select Subcommittee to Investigate the Remaining Questions Surrounding January 6, 2021', 'Committee on Homeland Security: Cybersecurity and Infrastructure Protection', 'Committee on the Judiciary: Courts, Intellectual Property, Artificial Intelligence, and the Internet', 'Committee on the Judiciary: Crime and Federal Government Surveillance'], 'M001225': ['Committee on Energy and Commerce', 'Committee on Energy and Commerce: Oversight and Investigations', 'Committee on Energy and Commerce: Energy', 'Committee on Energy and Commerce: Commerce, Manufacturing, and Trade'], 'L000607': ['Committee on Financial Services', 'Committee on Financial Services: Oversight and Investigations', 'Committee on Financial Services: National Security, Illicit Finance, and  International Financial Institutions', 'Committee on Financial Services: Digital Assets, Financial Technology, and Artificial Intelligence'], 'K000389': ['Committee on Armed Services', 'Committee on Oversight and Government Reform', 'Select Committee on the  Strategic Competition Between the United States and the Chinese Communist Party', 'Committee on Armed Services: Seapower and Projection Forces', 'Committee on Armed Services: Cyber, Information Technologies, and  Innovation', 'Committee on Oversight and Government Reform: Economic Growth, Energy Policy, and Regulatory Affairs', 'Committee on Oversight and Government Reform: Cybersecurity, Information Technology, and Government Innovation'], 'L000397': ['Committee on the Judiciary', 'Committee on Science, Space, and Technology', 'Committee on the Judiciary: Immigration Integrity, Security, and Enforcement', 'Committee on the Judiciary: Courts, Intellectual Property, Artificial Intelligence, and the Internet', 'Committee on the Judiciary: The Administrative State, Regulatory Reform, and Antitrust'], 'P000613': ['Committee on the Budget', 'Committee on Ways and Means', 'Committee on Ways and Means: Trade'], 'F000480': ['Committee on Homeland Security', 'Committee on Transportation and Infrastructure', 'Committee on Science, Space, and Technology', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials', 'Committee on Science, Space, and Technology: Research and Technology', 'Committee on Science, Space, and Technology: Space and Aeronautics'], 'C001059': ['Committee on Agriculture', 'Committee on Foreign Affairs', 'Committee on Agriculture: Forestry and Horticulture', 'Committee on Agriculture: Livestock, Dairy, and Poultry', 'Committee on Foreign Affairs: Europe'], 'V000129': ['Committee on Appropriations', 'Joint Committee on the Library', 'Committee on Appropriations: Agriculture, Rural Development, Food and Drug Administration, and Related Agencies', 'Committee on Appropriations: Defense', 'Chair: Committee on Appropriations: Legislative Branch'], 'O000019': ['Committee on the Budget', 'Committee on Energy and Commerce', 'Committee on Science, Space, and Technology', 'Committee on Energy and Commerce: Health', 'Committee on Energy and Commerce: Communications and Technology', 'Committee on Energy and Commerce: Commerce, Manufacturing, and Trade', 'Chairman: Committee on Science, Space, and Technology: Research and Technology'], 'C001112': ['Committee on Agriculture', 'Committee on Armed Services', 'Committee on Transportation and Infrastructure', 'Committee on Armed Services: Tactical Air and Land Forces', 'Committee on Armed Services: Strategic Forces', 'Committee on Transportation and Infrastructure: Aviation', 'Committee on Transportation and Infrastructure: Coast Guard and Maritime Transportation', 'Committee on Transportation and Infrastructure: Highways and Transit'], 'R000599': ['Committee on Energy and Commerce', 'Committee on Energy and Commerce: Health', 'Committee on Energy and Commerce: Communications and Technology', 'Committee on Energy and Commerce: Environment'], 'B001285': ['Committee on Natural Resources', 'Committee on Transportation and Infrastructure', "Committee on Veterans' Affairs", 'Committee on Natural Resources: Water, Wildlife and Fisheries', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Aviation', 'Committee on Transportation and Infrastructure: Highways and Transit', "Committee on Veterans' Affairs: Health"], 'W000830': ['Committee on Armed Services', 'Committee on Science, Space, and Technology', 'Committee on Armed Services: Seapower and Projection Forces', 'Committee on Armed Services: Strategic Forces', 'Committee on Armed Services: Cyber, Information Technologies, and  Innovation', 'Committee on Science, Space, and Technology: Space and Aeronautics'], 'C001080': ['Committee on the Budget', 'Committee on Ways and Means', 'Committee on Ways and Means: Health', 'Committee on Ways and Means: Work and Welfare', 'Committee on Ways and Means: Oversight'], 'R000620': ['Committee on Natural Resources', 'Committee on Science, Space, and Technology', 'Committee on Natural Resources: Energy and Mineral Resources', 'Committee on Natural Resources: Water, Wildlife and Fisheries', 'Committee on Science, Space, and Technology: Research and Technology', 'Committee on Science, Space, and Technology: Investigations and Oversight'], 'F000483': ['Committee on Transportation and Infrastructure', 'Committee on Science, Space, and Technology', 'Committee on Transportation and Infrastructure: Water Resources and Environment', 'Committee on Transportation and Infrastructure: Highways and Transit', 'Committee on Transportation and Infrastructure: Economic Development, Public Buildings, and Emergency Management', 'Committee on Transportation and Infrastructure: Railroads, Pipelines, and Hazardous Materials', 'Committee on Science, Space, and Technology: Energy'], 'C001123': ['Committee on Armed Services', 'Committee on Small Business', 'Committee on Armed Services: Military Personnel', 'Committee on Armed Services: Intelligence and Special Operations', 'Committee on Small Business: Contracting and Infrastructure', 'Committee on Small Business: Oversight, Investigations, and Regulations'], 'S000344': ['Committee on Financial Services', 'Committee on Foreign Affairs', 'Committee on Financial Services: Capital Markets', 'Committee on Financial Services: Financial Institutions', 'Committee on Financial Services: Digital Assets, Financial Technology, and Artificial Intelligence', 'Co

In [6]:

print(f"There are {len(df[df['current_member']=="yes"])} current members")

#df.sort_values(by='tenure_current', ascending=True).head()

There are 537 current members

Now you can start piloting your definitions here.

In [15]:
#get average vote for reps in house, reps in senate, dems in house, dems in senate

avg_vote = df.groupby(['chamber', 'partyName'])[['with_D_percent', 'with_R_percent']].mean()
print(avg_vote)

avg_vote = avg_vote.reset_index()
avg_vote['dummy'] = 1

avg_vote_pivot = avg_vote.pivot_table(
    index='dummy', # Use a dummy index since we want all data in one row
    columns=['chamber', 'partyName'],
    values=['with_D_percent', 'with_R_percent']
)

avg_vote_pivot = avg_vote_pivot.reset_index(drop=True)
avg_vote_pivot.columns = ['_'.join(map(str, col)).replace(' ', '_') for col in avg_vote_pivot.columns]

avg_vote_pivot.rename(columns=lambda x: x.replace('House_of_Representatives', 'avg_vote_H')
                                .replace('Senate', 'avg_vote_S')
                                .replace('_Democrat', '_D')
                                .replace('_Republican', '_R')
                                .replace('_Independent', '_I')
                                .replace('with_D_percent', 'with_D')
                                .replace('with_R_percent', 'with_R')
                                .replace('0_', '', 1) # Remove the dummy index column name part
                                , inplace=True)

avg_vote_pivot = avg_vote_pivot.reset_index(drop=True)

print(avg_vote_pivot)

                                      with_D_percent  with_R_percent
chamber                  partyName
House of Representatives Democrat          95.902326        4.097674
                         Republican         2.914414       97.085586
Senate                   Democrat               94.6             5.4
                         Independent            94.0             6.0
                         Republican         0.943396       99.056604
   with_D_avg_vote_H_D  with_D_avg_vote_H_R  with_D_avg_vote_S_D  \
0            95.902326             2.914414                 94.6

   with_D_avg_vote_S_I  with_D_avg_vote_S_R  with_R_avg_vote_H_D  \
0                 94.0             0.943396             4.097674

   with_R_avg_vote_H_R  with_R_avg_vote_S_D  with_R_avg_vote_S_I  \
0            97.085586                  5.4                  6.0

   with_R_avg_vote_S_R
0            99.056604

chamber                   partyName
House of Representatives  Democrat       46
                          Republican     46
Senate                    Democrat       36
                          Independent    24
                          Republican     48
Name: duration, dtype: int64

   max_tenure_H_D  max_tenure_H_R  max_tenure_S_D  max_tenure_S_I  \
0            46.0            46.0            36.0            24.0

   max_tenure_S_R
0            48.0

   count_D  count_I  count_R
0      260        2      275

            count_D  count_I  count_R
bioguideID      260        2      275

                   0
max_tenure_H_D  46.0
max_tenure_H_R  46.0
max_tenure_S_D  36.0
max_tenure_S_I  24.0
max_tenure_S_R  48.0
count_D          260
count_I            2
count_R          275
max_tenure_H_I   NaN

In [9]:
df_current = df[df['current_member']=="yes"]

df_current[df_current['committees'].isna()]

Empty DataFrame
Columns: [bioguideID, name, partyName, state, url, attribution, imageUrl, chamber, endYear, startYear, current_member, duration, tenure_all_time, tenure_all_time_party, tenure_current, tenure_current_party, party_all_time_count, party_current_count, tenure_current_party_percentile, Absent, Abstained, Both, Neither, with_D, with_R, vote_count, with_party_count, with_party_percent, with_party_rank, committees]
Index: []

[0 rows x 30 columns]