In [1]:
import requests
import os
import json
import time
import pandas as pd
import sys
import os
import numpy as np
from datetime import date
import modify_reps

In [2]:
try: 
    df = pd.read_json("congressmen.json")
except Exception as e:
    print("There is an issue with the congressmen.json. Quitting.")
    sys.exit()

try: 
    vote_df = pd.read_json("vote_avg.json")
except Exception as e:
    print("There is an issue with the vote_avg.json. Quitting.")
    sys.exit()

In [3]:
df[df['bioguideID']=="W000194"]

,bioguideID,name,partyName,state,url,attribution,imageUrl,chamber,endYear,startYear
489,W000194,"Watkins, Wes",Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,1991.0,1977
490,W000194,"Watkins, Wes",Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,2003.0,1997

Run all the modify_reps.py steps

In [4]:
df = modify_reps.update_endyear(df)
df = modify_reps.add_tenure(df)
df = modify_reps.normalize_name(df)
#df = modify_reps.only_current(df)
#df = modify_reps.merge_in_voting_records(df, vote_df)

df[df['bioguideID']=='W000194']

After processing, there are 0 na endYears

,bioguideID,name,partyName,state,url,attribution,imageUrl,chamber,endYear,startYear,current_member,duration,tenure_all_time,tenure_all_time_party,tenure_current,tenure_current_party,party_all_time_count,party_current_count
489,W000194,Wes Watkins,Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,1991,1977,no,14,892,377,<NA>,<NA>,1423,1148
490,W000194,Wes Watkins,Republican,Oklahoma,https://api.congress.gov/v3/member/W000194?for...,Collection of the U.S. House of Representatives,https://www.congress.gov/img/member/w000194_20...,House of Representatives,2003,1997,no,6,1794,845,<NA>,<NA>,1423,1148

Now for some stats, for your reference:

In [4]:

print(f"There are {len(df[df['current_member']=="yes"])} current members")

#df.sort_values(by='tenure_current', ascending=True).head()

There are 537 current members

Now you can start piloting your definitions here.

In [8]:
def replace_democratic(df):
    """Change Democratic party to Democrat"""
    df['partyName'] = df['partyName'].replace('Democratic', 'Democrat')
    return df

In [9]:
temp = replace_democratic(df)
temp.head()

,bioguideID,name,partyName,state,url,attribution,imageUrl,chamber,endYear,startYear,...,tenure_current,tenure_current_party,party_all_time_count,party_current_count,absent,abstain,against_party,with_party,missing_records,vote_count
0,M001233,Mark B. Messmer,Republican,Indiana,https://api.congress.gov/v3/member/M001233?for...,Image courtesy of the Member,https://www.congress.gov/img/member/677448630b...,House of Representatives,2027,2025,...,467,240,1423,275,6,0,2,210,0,218
1,R000617,Delia C. Ramirez,Democrat,Illinois,https://api.congress.gov/v3/member/R000617?for...,Image courtesy of the Member,https://www.congress.gov/img/member/684c235633...,House of Representatives,2027,2023,...,393,191,1434,260,18,0,7,193,0,218
2,S001232,Tim Sheehy,Republican,Montana,https://api.congress.gov/v3/member/S001232?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d8231fd...,Senate,2031,2025,...,308,142,1423,275,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,L000570,Ben Ray Luján,Democrat,New Mexico,https://api.congress.gov/v3/member/L000570?for...,Image courtesy of the Member,https://www.congress.gov/img/member/l000570_20...,Senate,2027,2021,...,308,165,1434,260,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,H001089,Josh Hawley,Republican,Missouri,https://api.congress.gov/v3/member/H001089?for...,NaN,https://www.congress.gov/img/member/h001089_20...,Senate,2031,2019,...,169,70,1423,275,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>